### ISSUE TITLE
Add 2 more sites

### ISSUE THREAD

**Issue by RixInGithub** [humiaozuzu/awesome-flask#223]
Hi guys,

I want you to add these two sites:

- https://accounts.nevium.repl.co/
- https://forums.nevium.repl.co/

They are all made **by me**, so you could freely add these sites.

**Comment by pathakvishal132** [comment]
Hey is this still an issue ? Can i contribute right now ?

**Comment by ah-ring** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by RixInGithub** [comment]
Nevermind. Old me :rofl:
