### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by clozinski** [humiaozuzu/awesome-flask#78]
Very nice piece of work.   What is the license for using this content?

Regards
Chris

**Comment by clozinski** [comment]
May I please use the awesome Flask data?

I run [Blogory.org/python](http://blogory.org/python), the world’s largest Python directory.   It is a free service. 

It is very easy for me to import your directory, integrate with the rest of the system, and link back to you. 

May I?

Chris

**Comment by clozinski** [comment]
Hi.
Awesome Django released under an open source license.  

Warm Regards
Chris

**Comment by humiaozuzu** [comment]
yes
